#!/usr/bin/env bash

cur_path="$(dirname ${BASH_SOURCE[0]})"
source "$cur_path/common.sh"

# check all proxies are connected.
for i in $(seq 0 $PROXY_COUNT); do 

  if [ $i -eq $PROXY_COUNT ]; then break; fi

  node_full_name="${PROXY_BASENAME}-${i}"
  node_host="${node_full_name}.${PROXY_SERVICE}"

  nc -zv "$node_host" $PG_GTM_PORT &> /dev/null
  assert $? "Cluster not ready, failed to connect to proxy at $node_host" >> /dev/stderr || exit $?
done