#!/usr/bin/env bash
# Checks if the gtm is alive and connected.
cur_path="$(dirname ${BASH_SOURCE[0]})"
source "$cur_path/common.sh"

# first check that the gtm is alive.
ping "$GTM_SERVICE" -s 1 -c 1 -W 1 &> /dev/null
assert $? "Cluster not ready, failed to ping gtm host @ $GTM_SERVICE" >> /dev/stderr || exit 1