#!/usr/bin/env bash
# Checks if all datanodes are alive and conneced to the network.
# thid file will only run on coordinators.
cur_path="$(dirname ${BASH_SOURCE[0]})"
source "$cur_path/common.sh"

# check all datanodes are connected.
for i in $(seq 0 $DATANODE_COUNT); do 
  if [ $i -eq $DATANODE_COUNT ]; then break; fi
  node_full_name="${DATANODE_BASENAME}-${i}"
  node_host="${node_full_name}.${DATANODE_SERVICE}"

  nc -zv "$node_host" $PG_PORT &> /dev/null
  assert $? "$LOGGING_PREFIX Cluster not ready, failed to connect to datanode at $node_host" >> /dev/stderr || exit $?
done