#!/usr/bin/env bash
# Initialize the node configuration.
cur_path="$(dirname ${BASH_SOURCE[0]})"
source "$cur_path/common.sh"
log:info "Initializing node configuration for $NODE_TYPE @ $PG_NODE"

node_config_file=""
config_target_file=""

case "$NODE_TYPE" in
gtm)
  config_target_file="${PGDATA}/gtm.conf"
  node_config_file="/config/config_append_gtm"
  ;;
datanode)
  config_target_file="${PGDATA}/postgresql.conf"
  node_config_file="/config/config_append_datanode"
  ;;
coordinator)
  config_target_file="${PGDATA}/postgresql.conf"
  node_config_file="/config/config_append_coordinator"
  ;;
proxy)
  config_target_file="${PGDATA}/gtm_proxy.conf"
  node_config_file="/config/config_append_proxy"
  ;;
*)
  log:error "Node configuration dose not exist for type $NODE_TYPE, error in condfig."
  exit 1
  ;;
esac

cat "/config/config_append_internal_global" >> "$config_target_file"
assert $? "Failed to append internal global configuration to $config_target_file" || exit $?
cat "$node_config_file" >> "$config_target_file"
assert $? "Failed to append node configuration file $node_config_file to $config_target_file" || exit $?

log:info "Node configuration added to $config_target_file"
