#!/usr/bin/env bash
# Initialize the host connection to allow all networks,
# since we are in kuberntes, the assumption is the current
# network is a trusted network.

export PG_AUTH_METHOD="trust"
if [ -n "$PGPASSWORD" ]; then
  PG_AUTH_METHOD="${AUTH_TYPE}"
  echo "$LOGGING_PREFIX Added network config to allow password protected connections."
else 
  echo "$LOGGING_PREFIX WARNING: Superuser password not found, set config to allow all connection."
fi

echo "host all all all $PG_AUTH_METHOD" >> "${PGDATA}/pg_hba.conf"

