#!/usr/bin/env bash

cur_path="$(dirname ${BASH_SOURCE[0]})"
source "$cur_path/common.sh"

function log() {
  echo "$LOGGING_PREFIX" "$@"
}

log:info "Waiting for database to be ready..."
"$cur_path/wait_for_connection" "$EXTERNAL_SERVICE" "$PG_PORT"
assert $? "Aborted, timed out while waiting for database to be ready @" "$EXTERNAL_SERVICE:$PG_PORT" || exit $?

function is_initialized() {
  local dose_state_table_exist=""
  dose_state_table_exist=$(psql -t -c "
SELECT EXISTS (
   SELECT 1
   FROM   information_schema.tables 
   WHERE  table_schema = 'postgres_xl_helm'
   AND    table_name = 'state'
   );
" | tr -d '[[:space:]]')

  if [ "$dose_state_table_exist" == "f" ]; then
    return 0
  fi

  return 1
}

function initialize_pgxl_state() {
  psql -c "
CREATE SCHEMA IF NOT EXISTS postgres_xl_helm;
DROP TABLE IF EXISTS postgres_xl_helm.state;
CREATE TABLE postgres_xl_helm.state AS (SELECT 'initialized' as key, 'ok' as value);
  " || return $?
}

function run_scripts_that_match() {
  local pattern="$1"
  local src_path="$(realpath "$2")"

  log:info "Searching for and executing scripts that match pattern '$pattern' in folder '$src_path'"
  local scripts=""
  scripts="$(find "$src_path" -maxdepth 1 -name "$pattern" | sort)"
  scripts=($scripts)

  local is_found=0

  for fpath in "${scripts[@]}"; do
    is_found=1
    
    local fname=$(basename "$fpath")
    local fileext=${fname##*.}

    case $fileext in
    sh)
      log:info "Executing bash script $fpath:"
      "$fpath"
      assert $? "Failed when executing init script file $fpath. Exiting... " || return $?
      ;;
    sql)
      log:info "Calling psql to execute script in $fpath:"
      local sql_script=""
      sql_script=$(cat "$fpath")
      psql -c "$sql_script"
      assert $? "Failed when executing init script file $fpath. Exiting... " || return $?
      ;;
    *)
      log:warning "Cannot invoke filename with extension $fileext, skipping. Allowed extensions [sql, sh]"
      ;;
    esac
  done

  if [ $is_found -eq 0 ]; then
    log:info "No scripts found."
  else
    log:info "Done."
  fi
}

pg_isready
assert $? "Database Port is ready but database is not (pg_isready failed) @" "$EXTERNAL_SERVICE:$PG_PORT" || exit $?

is_initialized
db_already_initialized=$?

if [ $db_already_initialized -eq 0 ]; then
  log:info "Database has not been initialized, calling init scripts.."

  log:info "Invoking init scripts.."
  run_scripts_that_match "init_*" "/load_scripts"
  assert $? "Initialization scripts failed, exiting." || exit $?

  log:info "Creating db postgres-xl-helm state tables"
  initialize_pgxl_state
  assert $? "Failed to initialize database for postgres-xl helm chart state." || exit $?
else
  log:info "Database already initialized. Skipping init scripts."
fi

log:info "Invoking startup scripts.."
run_scripts_that_match "startup_*" "/load_scripts"
assert $? "Startup scripts failed, exiting." || exit $?
