#!/usr/bin/env bash
cur_path="$(dirname ${BASH_SOURCE[0]})"
source "$cur_path/common.sh"

assert 2 "This is an error with stack"

function lama(){
  assert 2 "This is an error with stack in a function."
}

lama